"""create initial schema

Revision ID: eb58f41bd392
Revises: 
Create Date: 2026-09-11 22:27:27.009082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb58f41bd392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payee',
    sa.Column('payee_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('payee_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('payee_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=75), nullable=True),
    sa.Column('transfer_transaction_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('transfer_transaction_id IS NULL OR transfer_transaction_id != transaction_id', name='ck_transaction_transfer_not_self'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name='fk_transaction_account'),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.payee_id'], name='fk_transaction_payee', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_transaction_id'], ['transaction.transaction_id'], name='fk_transaction_transfer'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_split',
    sa.Column('transaction_split_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name='fk_transaction_split_category', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], name='fk_transaction_split_transaction'),
    sa.PrimaryKeyConstraint('transaction_split_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_split')
    op.drop_table('transaction')
    op.drop_table('payee')
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
